### ISSUE TITLE
npm error with latest tag

### ISSUE THREAD

**Issue by nuudles** [Wonderfall/docker-rtorrent-flood#1]
Hello, I've been using your docker image for a while now to great success! I think the latest tag broke something though, as I can't log in to my Flood server anymore. These are the errors that I get when I try:

```
Flood server starting on http://undefined:3000.

/usr/flood/node_modules/argon2/argon2.js:88
      m: memoryCost, t: timeCost, p: parallelism
      ^

TypeError: Cannot destructure property `m` of 'undefined' or 'null'.
    at Object.verify (/usr/flood/node_modules/argon2/argon2.js:90:7)
    at db.findOne.exec (/usr/flood/server/models/Users.js:25:10)
    at newArguments.(anonymous function) (/usr/flood/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/flood/node_modules/nedb/lib/datastore.js:518:14)
    at callback (/usr/flood/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/flood/node_modules/nedb/lib/cursor.js:193:12
    at /usr/flood/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/usr/flood/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /usr/flood/node_modules/nedb/lib/datastore.js:323:11
    at fn (/usr/flood/node_modules/nedb/node_modules/async/lib/async.js:582:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌──────────────────────────────────────────────┐
│           npm update check failed            │
│     Try running with sudo or get access      │
│     to the local update config store via     │
│ sudo chown -R $USER:$(id -gn $USER) /.config │
└──────────────────────────────────────────────┘

> flood@1.0.0 start /usr/flood
> node server/bin/start.js

Flood server starting on http://undefined:3000.
```

**Comment by Yiipanny** [comment]
the issue is same to me , could not login in .
